[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easy_opcua"
version = "1.0.0"  # <--- Hardcoded static version
description = "OPC UA server and client with easy tag handling"
readme = "README.md"
requires-python = ">=3.13"
license = {text = "MIT"}
authors = [
    {name = "Gabor, Baroczi", email = "baroczi.gabor@gmail.com"}
]


dependencies = [
    "asyncua>=1.1.8",
    "pydantic>=2.0.0",
]

[tool.setuptools.packages.find]
include = ["easy_opcua*"]
# [project.optional-dependencies]
# dev = [
#     "pytest>=7.0",
#     "black>=24.0",
#     "pyinstaller",
# ]
# 
# [tool.black]
# line-length = 88
# 
# [tool.isort]
# profile = "black"